---
- name: Install tinc (RedHat)
  yum: name=tinc state=present
  when: ansible_distribution in ('CentOS', 'RedHat')
- name: Install tinc (Fedora)
  dnf: name=tinc state=present
  when: ansible_distribution == 'Fedora'
- name: install tinc (Arch)
  package: name=tinc state=present
  when: ansible_distribution in 'Archlinux'
- name: install tinc (Debian)
  apt: name=tinc state=present
  when: ansible_distribution in ('Debian', 'Ubuntu')
